/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Plane202']: THREE.Mesh
    ['Plane202_1']: THREE.Mesh
    ['Plane202_2']: THREE.Mesh
    ['Plane202_3']: THREE.Mesh
  }
  materials: {
    Dirt: THREE.MeshStandardMaterial
    Red: THREE.MeshStandardMaterial
    ['Fire Station Windows']: THREE.MeshStandardMaterial
    ['Fire Station Boards']: THREE.MeshStandardMaterial
  }
}

export default function Model ({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('models/fire-0.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane202.geometry} material={materials.Dirt} />
        <mesh castShadow receiveShadow geometry={nodes.Plane202_1.geometry} material={materials.Red} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane202_2.geometry}
          material={materials['Fire Station Windows']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane202_3.geometry}
          material={materials['Fire Station Boards']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/fire-0.glb')
