/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane112: THREE.Mesh
    Plane112_1: THREE.Mesh
    Plane112_2: THREE.Mesh
    Plane112_3: THREE.Mesh
    Plane112_4: THREE.Mesh
    Plane112_5: THREE.Mesh
  }
  materials: {
    Dirt: THREE.MeshStandardMaterial
    ['HighRise::Windows']: THREE.MeshStandardMaterial
    ['HighRise::Walls']: THREE.MeshStandardMaterial
    ['HighRise::Edges']: THREE.MeshStandardMaterial
    ['HighRise::RedLight']: THREE.MeshStandardMaterial
    Grass: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/office-1.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane112.geometry} material={materials.Dirt} />
        <mesh castShadow receiveShadow geometry={nodes.Plane112_1.geometry} material={materials['HighRise::Windows']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane112_2.geometry} material={materials['HighRise::Walls']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane112_3.geometry} material={materials['HighRise::Edges']} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane112_4.geometry}
          material={materials['HighRise::RedLight']}
        />
        <mesh castShadow receiveShadow geometry={nodes.Plane112_5.geometry} material={materials.Grass} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/office-1.glb')
