/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Plane084']: THREE.Mesh
    ['Plane084_1']: THREE.Mesh
    ['Plane084_2']: THREE.Mesh
    ['Plane084_3']: THREE.Mesh
    ['Plane084_4']: THREE.Mesh
    ['Plane084_5']: THREE.Mesh
    ['Plane084_6']: THREE.Mesh
    ['Plane084_7']: THREE.Mesh
    ['Plane084_8']: THREE.Mesh
  }
  materials: {
    Grass: THREE.MeshStandardMaterial
    Dirt: THREE.MeshStandardMaterial
    ['Dog Park Fence']: THREE.MeshStandardMaterial
    ['Dog Park Ramp']: THREE.MeshStandardMaterial
    ['Dog 1']: THREE.MeshStandardMaterial
    ['Dog 2']: THREE.MeshStandardMaterial
    ['Dog Park Tube']: THREE.MeshStandardMaterial
    Rust: THREE.MeshStandardMaterial
    ['Memorial Park Benches']: THREE.MeshStandardMaterial
  }
}

export default function Model ({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/park-dog.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane084.geometry} material={materials.Grass} />
        <mesh castShadow receiveShadow geometry={nodes.Plane084_1.geometry} material={materials.Dirt} />
        <mesh castShadow receiveShadow geometry={nodes.Plane084_2.geometry} material={materials['Dog Park Fence']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane084_3.geometry} material={materials['Dog Park Ramp']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane084_4.geometry} material={materials['Dog 1']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane084_5.geometry} material={materials['Dog 2']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane084_6.geometry} material={materials['Dog Park Tube']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane084_7.geometry} material={materials.Rust} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane084_8.geometry}
          material={materials['Memorial Park Benches']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/park-dog.glb')
