/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Plane035']: THREE.Mesh
    ['Plane035_1']: THREE.Mesh
    ['Plane035_2']: THREE.Mesh
    ['Plane035_3']: THREE.Mesh
    ['Plane035_4']: THREE.Mesh
    ['Plane035_5']: THREE.Mesh
    ['Plane035_6']: THREE.Mesh
    ['Plane035_7']: THREE.Mesh
    ['Plane035_8']: THREE.Mesh
    ['Plane035_9']: THREE.Mesh
    ['Plane035_10']: THREE.Mesh
    ['Plane035_11']: THREE.Mesh
    ['Plane035_12']: THREE.Mesh
    ['Plane035_13']: THREE.Mesh
    ['Plane035_14']: THREE.Mesh
  }
  materials: {
    Dirt: THREE.MeshStandardMaterial
    ['Fine-Dining-Door']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Dining Wood']: THREE.MeshStandardMaterial
    ['Dining Table']: THREE.MeshStandardMaterial
    ['Dining Stripes']: THREE.MeshStandardMaterial
    ['Dining Light']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Dining Heat Lamp Base']: THREE.MeshStandardMaterial
    ['Dining Heat Lamp Flame']: THREE.MeshStandardMaterial
    ['Dining Bush']: THREE.MeshStandardMaterial
    Silverware: THREE.MeshStandardMaterial
    ['Dining Fire Pit']: THREE.MeshStandardMaterial
    ['Dining Fire']: THREE.MeshStandardMaterial
  }
}

export default function Model ({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('models/restaurant-2.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane035.geometry} material={materials.Dirt} />
        <mesh castShadow receiveShadow geometry={nodes.Plane035_1.geometry} material={materials['Fine-Dining-Door']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane035_2.geometry} material={materials['Material.010']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane035_3.geometry} material={materials['Material.014']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane035_4.geometry} material={materials['Dining Wood']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane035_5.geometry} material={materials['Dining Table']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane035_6.geometry} material={materials['Dining Stripes']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane035_7.geometry} material={materials['Dining Light']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane035_8.geometry} material={materials['Material.011']} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035_9.geometry}
          material={materials['Dining Heat Lamp Base']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035_10.geometry}
          material={materials['Dining Heat Lamp Flame']}
        />
        <mesh castShadow receiveShadow geometry={nodes.Plane035_11.geometry} material={materials['Dining Bush']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane035_12.geometry} material={materials.Silverware} />
        <mesh castShadow receiveShadow geometry={nodes.Plane035_13.geometry} material={materials['Dining Fire Pit']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane035_14.geometry} material={materials['Dining Fire']} />
      </group>
    </group>
  )
}

useGLTF.preload('models/restaurant-2.glb')
