/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane226: THREE.Mesh
    Plane226_1: THREE.Mesh
    Plane226_2: THREE.Mesh
    Plane226_3: THREE.Mesh
    Plane226_4: THREE.Mesh
    Plane226_5: THREE.Mesh
    Plane226_6: THREE.Mesh
    Plane226_7: THREE.Mesh
    Plane226_8: THREE.Mesh
    Plane226_9: THREE.Mesh
    Plane226_10: THREE.Mesh
    Plane226_11: THREE.Mesh
    Plane226_12: THREE.Mesh
    Plane226_13: THREE.Mesh
    Plane226_14: THREE.Mesh
    Plane226_15: THREE.Mesh
    Plane226_16: THREE.Mesh
    Plane226_17: THREE.Mesh
    Plane226_18: THREE.Mesh
  }
  materials: {
    Dirt: THREE.MeshStandardMaterial
    ['Drive Thru Menu']: THREE.MeshStandardMaterial
    ['Drive Thru Menu Screen']: THREE.MeshStandardMaterial
    ['Drive Thru Awning Secondary']: THREE.MeshStandardMaterial
    ['Drive Thru Awning Primary']: THREE.MeshStandardMaterial
    ['Drive Thru Building']: THREE.MeshStandardMaterial
    ['Drive Thru Trim']: THREE.MeshStandardMaterial
    ['Drive Thru Window']: THREE.MeshStandardMaterial
    ['Drive Thru Sign Pole']: THREE.MeshStandardMaterial
    ['Drive Thru Wooden Pole']: THREE.MeshStandardMaterial
    ['Drive Thru Road Stripe']: THREE.MeshStandardMaterial
    ['Drive Thru Speaker']: THREE.MeshStandardMaterial
    ['Drive Thru Speaker Trim']: THREE.MeshStandardMaterial
    ['Drive Thru Text']: THREE.MeshStandardMaterial
    ['Drive Thru Burger Bun']: THREE.MeshStandardMaterial
    ['Drive Thru Burger Patty']: THREE.MeshStandardMaterial
    ['Drive Thru Fry']: THREE.MeshStandardMaterial
    ['Drive Thru Fry Container']: THREE.MeshStandardMaterial
    ['Drive Thru Road']: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/restaurant-0.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane226.geometry} material={materials.Dirt} />
        <mesh castShadow receiveShadow geometry={nodes.Plane226_1.geometry} material={materials['Drive Thru Menu']} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane226_2.geometry}
          material={materials['Drive Thru Menu Screen']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane226_3.geometry}
          material={materials['Drive Thru Awning Secondary']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane226_4.geometry}
          material={materials['Drive Thru Awning Primary']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane226_5.geometry}
          material={materials['Drive Thru Building']}
        />
        <mesh castShadow receiveShadow geometry={nodes.Plane226_6.geometry} material={materials['Drive Thru Trim']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane226_7.geometry} material={materials['Drive Thru Window']} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane226_8.geometry}
          material={materials['Drive Thru Sign Pole']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane226_9.geometry}
          material={materials['Drive Thru Wooden Pole']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane226_10.geometry}
          material={materials['Drive Thru Road Stripe']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane226_11.geometry}
          material={materials['Drive Thru Speaker']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane226_12.geometry}
          material={materials['Drive Thru Speaker Trim']}
        />
        <mesh castShadow receiveShadow geometry={nodes.Plane226_13.geometry} material={materials['Drive Thru Text']} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane226_14.geometry}
          material={materials['Drive Thru Burger Bun']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane226_15.geometry}
          material={materials['Drive Thru Burger Patty']}
        />
        <mesh castShadow receiveShadow geometry={nodes.Plane226_16.geometry} material={materials['Drive Thru Fry']} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane226_17.geometry}
          material={materials['Drive Thru Fry Container']}
        />
        <mesh castShadow receiveShadow geometry={nodes.Plane226_18.geometry} material={materials['Drive Thru Road']} />
      </group>
    </group>
  )
}

useGLTF.preload('/restaurant-0.glb')
