/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['road-intersection_1']: THREE.Mesh
    ['road-intersection_2']: THREE.Mesh
    ['road-intersection_3']: THREE.Mesh
  }
  materials: {
    ['Road::Tar']: THREE.MeshStandardMaterial
    ['Road::Stripe']: THREE.MeshStandardMaterial
    Dirt: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/road-intersection.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.5, 0, -0.5]} rotation={[Math.PI, -3.9e-7, Math.PI]} scale={[0.75, 0.10000005, 0.75]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['road-intersection_1'].geometry}
          material={materials['Road::Tar']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['road-intersection_2'].geometry}
          material={materials['Road::Stripe']}
        />
        <mesh castShadow receiveShadow geometry={nodes['road-intersection_3'].geometry} material={materials.Dirt} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/road-intersection.glb')
