/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane178: THREE.Mesh
    Plane178_1: THREE.Mesh
    Plane178_2: THREE.Mesh
    Plane178_3: THREE.Mesh
    Plane178_4: THREE.Mesh
    Plane178_5: THREE.Mesh
    Plane178_6: THREE.Mesh
    Plane178_7: THREE.Mesh
  }
  materials: {
    Dirt: THREE.MeshStandardMaterial
    ['Rust::Market::BushPlanter']: THREE.MeshStandardMaterial
    ['Rust::Market::Bush']: THREE.MeshStandardMaterial
    ['Rust::Market::Stripes']: THREE.MeshStandardMaterial
    ['Rust::Market::OtherStripes']: THREE.MeshStandardMaterial
    ['Rust::Market::Walls']: THREE.MeshStandardMaterial
    ['Rust::Market::Planters']: THREE.MeshStandardMaterial
    ['Rust::Market::Windows']: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/shop-small.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane178.geometry} material={materials.Dirt} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane178_1.geometry}
          material={materials['Rust::Market::BushPlanter']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane178_2.geometry}
          material={materials['Rust::Market::Bush']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane178_3.geometry}
          material={materials['Rust::Market::Stripes']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane178_4.geometry}
          material={materials['Rust::Market::OtherStripes']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane178_5.geometry}
          material={materials['Rust::Market::Walls']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane178_6.geometry}
          material={materials['Rust::Market::Planters']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane178_7.geometry}
          material={materials['Rust::Market::Windows']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/shop-small.glb')
