/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube024: THREE.Mesh
    Cube024_1: THREE.Mesh
    Cube024_2: THREE.Mesh
    Cube024_3: THREE.Mesh
    Cube024_4: THREE.Mesh
    Cube024_5: THREE.Mesh
    Cube024_6: THREE.Mesh
    Cube024_7: THREE.Mesh
    Cube024_8: THREE.Mesh
    Cube024_9: THREE.Mesh
    Cube024_10: THREE.Mesh
    Cube024_11: THREE.Mesh
    Cube024_12: THREE.Mesh
    Cube024_13: THREE.Mesh
    Cube024_14: THREE.Mesh
    Cube024_15: THREE.Mesh
    Cube024_16: THREE.Mesh
    Cube024_17: THREE.Mesh
    Cube024_18: THREE.Mesh
    Cube024_19: THREE.Mesh
    Cube024_20: THREE.Mesh
  }
  materials: {
    ['Farm Stand Wood']: THREE.MeshStandardMaterial
    Grass: THREE.MeshStandardMaterial
    Dirt: THREE.MeshStandardMaterial
    ['Awning White']: THREE.MeshStandardMaterial
    ['Awning Red']: THREE.MeshStandardMaterial
    ['Crate.001']: THREE.MeshStandardMaterial
    Apple: THREE.MeshStandardMaterial
    Pear: THREE.MeshStandardMaterial
    Carrot: THREE.MeshStandardMaterial
    Blueberry: THREE.MeshStandardMaterial
    Lemon: THREE.MeshStandardMaterial
    ['Crate Black']: THREE.MeshStandardMaterial
    ['Crate Green']: THREE.MeshStandardMaterial
    Barrel: THREE.MeshStandardMaterial
    Tomato: THREE.MeshStandardMaterial
    ['Tomato Stem']: THREE.MeshStandardMaterial
    ['Sign Text']: THREE.MeshStandardMaterial
    ['Farm Stand Sign Wood']: THREE.MeshStandardMaterial
    ['Awning Green']: THREE.MeshStandardMaterial
    ['Fruirt Holder']: THREE.MeshStandardMaterial
    ['Barel Metal']: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/shop-market.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1, 0, 0]} rotation={[0, -Math.PI / 4, 0]} scale={[0.05, 0.04, -0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube024.geometry} material={materials['Farm Stand Wood']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_1.geometry} material={materials.Grass} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_2.geometry} material={materials.Dirt} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_3.geometry} material={materials['Awning White']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_4.geometry} material={materials['Awning Red']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_5.geometry} material={materials['Crate.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_6.geometry} material={materials.Apple} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_7.geometry} material={materials.Pear} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_8.geometry} material={materials.Carrot} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_9.geometry} material={materials.Blueberry} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_10.geometry} material={materials.Lemon} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_11.geometry} material={materials['Crate Black']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_12.geometry} material={materials['Crate Green']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_13.geometry} material={materials.Barrel} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_14.geometry} material={materials.Tomato} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_15.geometry} material={materials['Tomato Stem']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_16.geometry} material={materials['Sign Text']} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_17.geometry}
          material={materials['Farm Stand Sign Wood']}
        />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_18.geometry} material={materials['Awning Green']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_19.geometry} material={materials['Fruirt Holder']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_20.geometry} material={materials['Barel Metal']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/shop-market.glb')
