name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Rebase
      uses: DeeDeeG/rebase-github-action@1.0-beta3
      with:
        base_ref: deploy
        head_branch: main

    - name: Build
      run: |
        npm install
        npm run build
        
    - name: Add and Commit
      uses: EndBug/add-and-commit@v7
      with:
        add: 'docs'
        branch: deploy
        pull: --rebase
        push: -u origin deploy --force
