name: NodeJS with Webpack

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: deploy

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 16.13.1

    - name: Build
      run: |
        npm install
        npm run build
        git add .
        git commit -m "updating deployment"
        git push --force
